---
- name: input--for-ec2-region Playbook
  hosts: all
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: false
  tasks:
    - name: take input
      package: 
        name: "{{package}}"
        state: latest