---
- name: Wordpress-Installation-Ansible
  hosts: localhost
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: false
  tasks: Install packages for Wordpress
    - name: name of packages for Wordpress
      package: 
        - epel-release  
        - wget
        - unzip
        - mariadb-server
        - httpd
      state: present



    - name: download wordpress
      get_url
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp


    - name: Unzip Wordpress
      unarchive:
        remote_src: yes
        dest: /var/www/html
  

    - name: Start service httpd, if not started
      service:
        name: httpd
        state: started