- name: Create Route53     
  hosts: localhost
  become: true
  become_method: sudo
  tasks:
  - route53:
      state: present
      zone: 'devops-chicago.com'
      record: wordpress.devops-chicago.com
      type: A
      ttl: 7200
      value: 18.195.177.76